# Generated by Django 4.2.7 on 2026-09-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aprobado", "Aprobado"),
                    ("Rechazado", "Rechazado"),
                    ("Pendiente", "Pendiente"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aprobado", "Aprobado"),
                    ("Rechazado", "Rechazado"),
                    ("Pendiente", "Pendiente"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aprobado", "Aprobado"),
                    ("Rechazado", "Rechazado"),
                    ("Pendiente", "Pendiente"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
