# Generated by Django 5.2.17 on 2026-09-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_accommodation_status_alter_activity_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodationtype",
            name="description",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="contact_phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
