# Generated by Django 5.2.17 on 2026-09-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_accommodationtype_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodationtype",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
