# Generated by Django 5.2.17 on 2026-09-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvallog",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
